<a href="https://colab.research.google.com/github/SeohaLim0501/AICE-Study/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 01: 파이썬 데이터 분석 라이브러리 활용하기

In [ ]:
import numpy as np
import pandas as pd

## Numpy

In [ ]:
a = np.array([1,2,3,4,5]) # numpy는 n차원 행렬 자료 구조인 ndarray를 사용
b = np.array([1, 2, '대한민국', '포르투갈'])
print(a) # 실행 결과가 리스트 형태로 출력
print(b) # 숫자와 문자를 혼합 사용하여 ndarray를 만들 경우 모든 내용을 문자열로 인식하여 출력

[1 2 3 4 5]
['1' '2' '대한민국' '포르투갈']

## Pandas

In [ ]:
# 판다스에서 대표적으로 사용하는 자료구조: 시리즈와 데이터프레임
# 시리즈: 변수명 = pd.Series(data, index = index, name = name)
s = pd.Series(['대한민국', '포르투갈','가나', '우루과이'], index = ['가', '나', '다', '라'], name = "2022 카다르월드컵 H조")
print(s)

가    대한민국
나    포르투갈
다      가나
라    우루과이
Name: 2022 카다르월드컵 H조, dtype: object

In [ ]:
# 데이터프레임은 시리즈가 여러 개 합쳐진 자료형
# Dictionary형과 List형으로 생성 가능

# Dictionary형
a1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]}) # Index와 Column 방식으로 생성: 딕셔너리의 Key가 Column name으로 지정됨
print(a1)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
a1

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
# List형
a2 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ["a", "b", "c"]) # Index와 Row 방식으로 생성
a2

   0  1  2
a  1  2  3
b  4  5  6
c  7  8  9

# Section 02: 데이터 불러오기

판다스는 다양한 형태의 데이터를 불러오기 위해 'read_XXX' 함수를 주로 사용합니다.  
예) read_csv, read_html, read_json

In [ ]:
# 변수 = pd.read_csv(filepath, encoding, ...)
# https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction 데이터 활용

import pandas as pd
import numpy as np

!wget -O flight.zip "https://www.kaggle.com/api/v1/datasets/download/shubhambathwal/flight-price-prediction"
!unzip -o flight.zip
!rm -f flight.zip
!rm -f business.csv economy.csv

--2026-10-25 04:15:00--  https://www.kaggle.com/api/v1/datasets/download/shubhambathwal/flight-price-prediction
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com:443/kaggle-data-sets/1957837/3228623/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261025%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261025T035628Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=3a44998c4f27fca65ea7d4bfc0e6eaa02f6d9af04043e4e484257fddc5b1ad718d2fc17495344f10b74e2922ab272a3737a944e1fc374921a132274563416c1bf36f23cfafb57340902927a4ba10c337e205e974823a00b302753ef50e79016ac8712bc13cb3804540e962e0ce24fe8e161d04b1056591d7e442b0755c52630385d9b34d8e0302b923fbba1b2faf09ce556fd4bc9ffe8a99941a1644b5152d1a337eca0884b0f30749c97659488e3cbe754e82d6805eae090430d84c9967c5ad85adf4130ed4e29e0cb00fb0e427f3bfbd05115a2cea6ce2d975becfa69c344f2841822f2673efc76c6b6a0f926c1c509106777d95cc127892499a8f9cb842fe [following]
--2026-10-25 04:15:00--  https://storage.googleapis.com/kaggle-data-sets/1957837/3228623/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261025%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261025T035628Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=3a44998c4f27fca65ea7d4bfc0e6eaa02f6d9af04043e4e484257fddc5b1ad718d2fc17495344f10b74e2922ab272a3737a944e1fc374921a132274563416c1bf36f23cfafb57340902927a4ba10c337e205e974823a00b302753ef50e79016ac8712bc13cb3804540e962e0ce24fe8e161d04b1056591d7e442b0755c52630385d9b34d8e0302b923fbba1b2faf09ce556fd4bc9ffe8a99941a1644b5152d1a337eca0884b0f30749c97659488e3cbe754e82d6805eae090430d84c9967c5ad85adf4130ed4e29e0cb00fb0e427f3bfbd05115a2cea6ce2d975becfa69c344f2841822f2673efc76c6b6a0f926c1c509106777d95cc127892499a8f9cb842fe
Resolving storage.googleapis.com (storage.googleapis.com)... 34.153.2.27, 34.3.0.27, 34.144.170.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.153.2.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4360218 (4.2M) [application/zip]
Saving to: ‘flight.zip’

flight.zip          100%[===================>]   4.16M  --.-KB/s    in 0.01s

2026-10-25 04:15:01 (304 MB/s) - ‘flight.zip’ saved [4360218/4360218]

Archive:  flight.zip
  inflating: Clean_Dataset.csv
  inflating: business.csv
  inflating: economy.csv

In [ ]:
flight = pd.read_csv('./Clean_Dataset.csv', encoding = "cp949") # Pandas의 DataFrame 형태로 저장
flight

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

# Section 03: 데이터 저장하기

In [ ]:
# to_csv 함수 사용

print(a2)
a2.to_csv('./result_a2.csv')

   0  1  2
a  1  2  3
b  4  5  6
c  7  8  9

In [ ]:
result = pd.read_csv('./result_a2.csv', encoding = "cp949")
result

  Unnamed: 0  0  1  2
0          a  1  2  3
1          b  4  5  6
2          c  7  8  9

In [ ]:
# read_csv 함수의 파라미터를 활용해 데이터프레임 정제

flight2 = pd.read_csv('./Clean_Dataset.csv', index_col = 'stops', usecols = ['stops', 'departure_time', 'arrival_time', 'destination_city'])
flight2

# index_col은 DataFrame의 Index로 사용할 CSV의 열을 지정하는 매개변수
# Column position으로도 지정 가능: ex) index_col = 3

# usecols는 반드시 index_col로 설정한 칼럼명을 포함해야 함

      departure_time   arrival_time destination_city
stops
zero         Evening          Night           Mumbai
zero   Early_Morning        Morning           Mumbai
zero   Early_Morning  Early_Morning           Mumbai
zero         Morning      Afternoon           Mumbai
zero         Morning        Morning           Mumbai
...              ...            ...              ...
one          Morning        Evening        Hyderabad
one        Afternoon          Night        Hyderabad
one    Early_Morning          Night        Hyderabad
one    Early_Morning        Evening        Hyderabad
one          Morning        Evening        Hyderabad

[300153 rows x 3 columns]

In [ ]:
# crosstab는 범주형 데이터 2개를 비교, 분석할 때 사용
# 두 변수의 조합별 데이터 개수를 세는 함수

pd.crosstab(index = flight.source_city, columns = flight.arrival_time)

arrival_time  Afternoon  Early_Morning  Evening  Late_Night  Morning  Night
source_city
Bangalore          6992           3154    14493        2673    10411  14338
Chennai            5152           1606    10830        1999     7106  12007
Delhi              8007           5262    14630        2143    13007  18294
Hyderabad          4816           1581    10539        2092     8854  12924
Kolkata            5941           2156    11304        2414     9595  14937
Mumbai             7231           1658    16527        2680    13762  19038

In [ ]:
# 개수 대신 비율을 출력할 경우 ex) normalize = 'index'
# 이 경우 index 별로 column 값들의 합이 1이 됨; 각 index의 합계로 나눔

pd.crosstab(index = flight.source_city, columns = flight.arrival_time, normalize = 'index')

arrival_time,Afternoon,Early_Morning,Evening,Late_Night,Morning,Night
source_city,,,,,,
Bangalore,0.134304,0.060583,0.278385,0.051344,0.199977,0.275408
Chennai,0.133127,0.041499,0.279845,0.051654,0.183618,0.310258
Delhi,0.130528,0.085780,0.238495,0.034935,0.212037,0.298225
Hyderabad,0.118022,0.038744,0.258271,0.051267,0.216978,0.316718
Kolkata,0.128185,0.046519,0.243899,0.052085,0.207025,0.322286
Mumbai,0.118743,0.027227,0.271397,0.044009,0.225992,0.312631

In [ ]:
# 전체 합계까지 출력할 경우 margins = True

pd.crosstab(index = flight.source_city, columns = flight.arrival_time, margins = True)

arrival_time,Afternoon,Early_Morning,Evening,Late_Night,Morning,Night,All
source_city,,,,,,,
Bangalore,6992,3154,14493,2673,10411,14338,52061
Chennai,5152,1606,10830,1999,7106,12007,38700
Delhi,8007,5262,14630,2143,13007,18294,61343
Hyderabad,4816,1581,10539,2092,8854,12924,40806
Kolkata,5941,2156,11304,2414,9595,14937,46347
Mumbai,7231,1658,16527,2680,13762,19038,60896
All,38139,15417,78323,14001,62735,91538,300153

In [ ]:
# 둘 다 사용할 경우 normalized 된 행/열은 margin 생략

pd.crosstab(index = flight.source_city, columns = flight.arrival_time, normalize = 'index', margins = True)

arrival_time,Afternoon,Early_Morning,Evening,Late_Night,Morning,Night
source_city,,,,,,
Bangalore,0.134304,0.060583,0.278385,0.051344,0.199977,0.275408
Chennai,0.133127,0.041499,0.279845,0.051654,0.183618,0.310258
Delhi,0.130528,0.085780,0.238495,0.034935,0.212037,0.298225
Hyderabad,0.118022,0.038744,0.258271,0.051267,0.216978,0.316718
Kolkata,0.128185,0.046519,0.243899,0.052085,0.207025,0.322286
Mumbai,0.118743,0.027227,0.271397,0.044009,0.225992,0.312631
All,0.127065,0.051364,0.260944,0.046646,0.209010,0.304971